First draft
melonproject/documentation pull request #2
Opened 2018-05-16 13:48 UTC by john-0x

2018-05-17 09:37 UTC, jennazenk requested changes

2018-05-17 09:37 UTC, jennazenk commented on chapters/asset_registrar.md
> +| Name | Type | Description |
table is repeated twice @john-0x

2018-05-17 09:37 UTC, jennazenk commented on chapters/asset_registrar.md
> +add more detail on: AR 1st, then price feed...
would delete internal comments/notes

2018-05-17 09:37 UTC, jennazenk commented on chapters/exchange.md
> +- ERCDex (0x-based)
Instead of: 
- RadarRelay (0x-based)
- ERCDex (0x-based)

I would say 

- 0x protocol (which gives access to all the 0x relayers)

2018-05-17 09:37 UTC, jennazenk commented on chapters/price_feed.md
> +Prospective Price Feed Operators (candidates) must offer a deposit or "stake" in Melon Tokens (MLN). Individual Price Feed Operators are then "selected" by the Melon Platform solely on the level of t
>"selected" by the Melon Platform 

would rephrase : "selected" by the Melon contracts

2018-05-24 07:45 UTC, jennazenk approved these changes

2018-05-24 07:58 UTC, travs approved these changes

2018-05-24 08:04 UTC, GauthamN approved these changes

2018-05-24 08:06 UTC, merged